wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/qflow_discrete.py
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1711562296.439035
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.5
      5: 0.13.11
      8:
      - 5
a_bins:
  desc: null
  value: 20
alpha:
  desc: null
  value: 1.0
autotune:
  desc: null
  value: true
batch_size:
  desc: null
  value: 128
buffer_size:
  desc: null
  value: 1000000
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: true
env_id:
  desc: null
  value: InvertedPendulum-v4
exp_name:
  desc: null
  value: qflow_discrete
gamma:
  desc: null
  value: 0.99
gfn_batch_size:
  desc: null
  value: 128
gfn_lr:
  desc: null
  value: 0.0005
gfn_num_states:
  desc: null
  value: 128
learning_starts:
  desc: null
  value: 5000.0
q_lr:
  desc: null
  value: 0.0005
q_steps:
  desc: null
  value: 1
seed:
  desc: null
  value: 1
target_entropy:
  desc: null
  value: 0.5
target_network_frequency:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 1000000
track:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: swish
wandb_project_name:
  desc: null
  value: advantage-diffusion
